# config.mk
#
# Product-specific compile-time definitions.
#
# CPU0
TARGET_NO_BOOTLOADER := true
TARGET_CPU_ABI := x86_64
TARGET_ARCH := x86_64
TARGET_ARCH_VARIANT := x86_64
# CPU1
TARGET_2ND_CPU_ABI := x86
TARGET_2ND_ARCH := x86
TARGET_2ND_ARCH_VARIANT := x86_64
# GFX
USE_OPENGL_RENDERER := true
TARGET_NO_KERNEL := false
TARGET_KERNEL_SOURCE := kernel/valve/jupiter
BOARD_KERNEL_IMAGE_NAME := kernel
TARGET_KERNEL_CONFIG := jupiter_defconfig
TARGET_KERNEL_ARCH := x86_64
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648
BOARD_USERDATAIMAGE_PARTITION_SIZE := 576716800
BOARD_CACHEIMAGE_PARTITION_SIZE := 69206016
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 512
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true
